package com.edu.msc.sliit.model;

import java.util.HashMap;

public class Sound {
	public static HashMap<String, String> sinhalaSounds=new HashMap<String, String>();
	static {
		sinhalaSounds.put("කි","./src/main/resources/static/audios/ki.mp3");
		sinhalaSounds.put("කී","./src/main/resources/static/audios/kii.mp3");		
		sinhalaSounds.put("අ","./src/main/resources/static/audios/a.mp3");		
		sinhalaSounds.put("ප්‍රා","./src/main/resources/static/audios/praaaa-Part 2.mp3");
		sinhalaSounds.put("දේ","./src/main/resources/static/audios/dhee-Part 2_1.mp3");
		sinhalaSounds.put("ශී","./src/main/resources/static/audios/shii-Part 2.mp3");
		sinhalaSounds.put("ය","./src/main/resources/static/audios/ya-Part 2.mp3");
		sinhalaSounds.put("ලෙ","./src/main/resources/static/audios/le-Part 2.mp3");
		sinhalaSounds.put("ස","./src/main/resources/static/audios/sa-Part 2.mp3");
		sinhalaSounds.put("වි","./src/main/resources/static/audios/vi-Part 2.mp3");
		sinhalaSounds.put("ම","./src/main/resources/static/audios/ma-Part 2.mp3");		
		sinhalaSounds.put("ධ්","./src/main/resources/static/audios/dh-Part 2_1.mp3");		
		sinhalaSounds.put("ග","./src/main/resources/static/audios/ga-Part 2.mp3");
		sinhalaSounds.put("ත","./src/main/resources/static/audios/tha-Part 2.mp3");		
		sinhalaSounds.put("ව","./src/main/resources/static/audios/va-Part 2.mp3");
		sinhalaSounds.put("පැ","./src/main/resources/static/audios/paaa-Part 2.mp3");
		sinhalaSounds.put("ති","./src/main/resources/static/audios/thi-Part 2.mp3");		
		sinhalaSounds.put("ශ","./src/main/resources/static/audios/sha-Part 2.mp3");
		sinhalaSounds.put("පා","./src/main/resources/static/audios/paa-Part 2.mp3");		
		sinhalaSounds.put("ල","./src/main/resources/static/audios/la-Part 2.mp3");
		sinhalaSounds.put("න","./src/main/resources/static/audios/na-Part 2.mp3");
		sinhalaSounds.put("බ","./src/main/resources/static/audios/ba-Part 2.mp3");
		sinhalaSounds.put("පු","./src/main/resources/static/audios/pu-Part 2.mp3");
		sinhalaSounds.put("රු","./src/main/resources/static/audios/ru-Part 2.mp3");		
		sinhalaSounds.put("මු","./src/main/resources/static/audios/mu-Part 2.mp3");
		sinhalaSounds.put("හ","./src/main/resources/static/audios/ha-Part 2.mp3");
		sinhalaSounds.put("ර","./src/main/resources/static/audios/ra-Part 2.mp3");
		sinhalaSounds.put("ජ","./src/main/resources/static/audios/ja-Part 2.mp3");				
		sinhalaSounds.put("ඒ","./src/main/resources/static/audios/e-Part 2.mp3");
		sinhalaSounds.put("ටා","./src/main/resources/static/audios/taa-Part 4.mp3");		
		sinhalaSounds.put("ගො","./src/main/resources/static/audios/go-Part 2.mp3");
		sinhalaSounds.put("නු","./src/main/resources/static/audios/nu-Part 2.mp3");		
		sinhalaSounds.put("වූ","./src/main/resources/static/audios/vu-Part 2.mp3");		
		sinhalaSounds.put("රා","./src/main/resources/static/audios/raa-Part 2.mp3");
		sinhalaSounds.put("ජ්","./src/main/resources/static/audios/j-Part 2.mp3");
		sinhalaSounds.put("න්","./src/main/resources/static/audios/n-Part 2.mp3");		
		sinhalaSounds.put("ත්‍ර","./src/main/resources/static/audios/thra-Part 2.mp3");		
		sinhalaSounds.put("ක්","./src/main/resources/static/audios/k-Part 2.mp3");
		sinhalaSounds.put("වී","./src/main/resources/static/audios/vii-Part 2.mp3");
		sinhalaSounds.put("භ","./src/main/resources/static/audios/ba-Part 2.mp3");		
		sinhalaSounds.put("ට","./src/main/resources/static/audios/ta-Part 2.mp3");		
		sinhalaSounds.put("පූ","./src/main/resources/static/audios/puu-Part 2.mp3");		
		sinhalaSounds.put("ර්","./src/main/resources/static/audios/r-Part 2.mp3");		
		sinhalaSounds.put("ණ","./src/main/resources/static/audios/na-Part 2.mp3");
		sinhalaSounds.put("ත්","./src/main/resources/static/audios/th-Part 2.mp3");		
		sinhalaSounds.put("ඛ","./src/main/resources/static/audios/ka-Part 2.mp3");		
		sinhalaSounds.put("ඛා","./src/main/resources/static/audios/kaa-Part 2.mp3");		
		sinhalaSounds.put("අ","./src/main/resources/static/audios/a-Part 2.mp3");
		sinhalaSounds.put("ප","./src/main/resources/static/audios/pa-Part 2.mp3");
		sinhalaSounds.put("ආ","./src/main/resources/static/audios/aa-Part 2_1.mp3");
		sinhalaSounds.put("කා","./src/main/resources/static/audios/kaa-Part 2.mp3");
		sinhalaSounds.put("ඝ","./src/main/resources/static/audios/ga-Part 2.mp3");
		sinhalaSounds.put("ස්","./src/main/resources/static/audios/s-Part 2.mp3");
		sinhalaSounds.put("දි","./src/main/resources/static/audios/di-Part 2_1.mp3");
		sinhalaSounds.put("යි","./src/main/resources/static/audios/yi-Part 2.mp3");
		sinhalaSounds.put("තු","./src/main/resources/static/audios/thu-Part 2.mp3");
		sinhalaSounds.put("ළ","./src/main/resources/static/audios/la-Part 2.mp3");		
		sinhalaSounds.put("ෂ","./src/main/resources/static/audios/sha-Part 2.mp3");		
		sinhalaSounds.put("ෂේ","./src/main/resources/static/audios/shee-Part 2.mp3");
		sinhalaSounds.put("නා","./src/main/resources/static/audios/naa-Part 2_1.mp3");
		sinhalaSounds.put("ඔ","./src/main/resources/static/audios/0-Part 2_1.mp3");		
		sinhalaSounds.put("සේ","./src/main/resources/static/audios/see-Part 2.mp3");	
		sinhalaSounds.put("රි","./src/main/resources/static/audios/ri-Part 2.mp3");		
		sinhalaSounds.put("ක","./src/main/resources/static/audios/ka-Part 2.mp3");
		sinhalaSounds.put("යු","./src/main/resources/static/audios/yu-Part 2.mp3");
		sinhalaSounds.put("මෙ","./src/main/resources/static/audios/me-Part 2.mp3");		
		sinhalaSounds.put("හෙ","./src/main/resources/static/audios/he-Part 2.mp3");
		sinhalaSounds.put("හා","./src/main/resources/static/audios/haa-Part 2.mp3");
		sinhalaSounds.put("නි","./src/main/resources/static/audios/ni-Part 2.mp3");
		sinhalaSounds.put("ධා","./src/main/resources/static/audios/dhaa-Part 4_1.mp3");
		sinhalaSounds.put("රී","./src/main/resources/static/audios/rii-Part 2.mp3");		
		sinhalaSounds.put("ගෙ","./src/main/resources/static/audios/ge-Part 2.mp3");	
		sinhalaSounds.put("ශ්","./src/main/resources/static/audios/sh-Part 2.mp3");
		sinhalaSounds.put("ඉ","./src/main/resources/static/audios/i-Part 2.mp3");		
		sinhalaSounds.put("ණි","./src/main/resources/static/audios/ni-Part 2.mp3");		
		sinhalaSounds.put("සෙ","./src/main/resources/static/audios/se-Part 2.mp3");		
		sinhalaSounds.put("ල්","./src/main/resources/static/audios/l-Part 2.mp3");
		sinhalaSounds.put("ලි","./src/main/resources/static/audios/li-Part 2.mp3");
		sinhalaSounds.put("පි","./src/main/resources/static/audios/pi-Part 2.mp3");		
		sinhalaSounds.put("වැ","./src/main/resources/static/audios/vaaaa-Part 2.mp3");			
		sinhalaSounds.put("මූ","./src/main/resources/static/audios/muu-Part 2.mp3");		
		sinhalaSounds.put("ලා","./src/main/resources/static/audios/lo-Part 2.mp3");		
		sinhalaSounds.put("ශ්‍ර","./src/main/resources/static/audios/shraa-Part 2.mp3");			
		sinhalaSounds.put("හි","./src/main/resources/static/audios/hi-Part 2.mp3");		
		sinhalaSounds.put("දැ","./src/main/resources/static/audios/daaa-Part 2.mp3");
		sinhalaSounds.put("වෙ","./src/main/resources/static/audios/ve-Part 2.mp3");
		sinhalaSounds.put("ද","./src/main/resources/static/audios/dha-Part 2_1.mp3");
		sinhalaSounds.put("මො","./src/main/resources/static/audios/mo-Part 2.mp3");		
		sinhalaSounds.put("වා","./src/main/resources/static/audios/vaa-Part 2.mp3");				
		sinhalaSounds.put("ශෙ","./src/main/resources/static/audios/she-Part 2.mp3");
		sinhalaSounds.put("ඩ","./src/main/resources/static/audios/da-Part 2_1.mp3");	
		sinhalaSounds.put("ගු","./src/main/resources/static/audios/gu-Part 2.mp3");		
		sinhalaSounds.put("කො","./src/main/resources/static/audios/ko-Part 2.mp3");		
		sinhalaSounds.put("ගෑ","./src/main/resources/static/audios/gaaaa-Part 2.mp3");				
		sinhalaSounds.put("ඩි","./src/main/resources/static/audios/dii-Part 2_1.mp3");		
		sinhalaSounds.put("දෙ","./src/main/resources/static/audios/dhe-Part 2_1.mp3");		
	}
}


